// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"GFBackend/controller"
	"GFBackend/model/dao"
	"GFBackend/service"
)

// Injectors from wire.go:

func InitializeUserManageController() (*controller.UserManageController, error) {
	userDAO := dao.NewUserDAO()
	userManageService := service.NewUserManageService(userDAO)
	userManageController := controller.NewUserManageController(userManageService)
	return userManageController, nil
}

func InitializeCommunityManageController() (*controller.CommunityManageController, error) {
	communityDAO := dao.NewCommunityDAO()
	communityManageService := service.NewCommunityManageService(communityDAO)
	communityManageController := controller.NewCommunityManageController(communityManageService)
	return communityManageController, nil
}
