// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package reqs

import (
	"GFBackend/controller"
	"GFBackend/model/dao"
	"GFBackend/service"
)

// Injectors from wire.go:

func InitializeUserManageController() (*controller.UserManageController, error) {
	userDAO := dao.NewUserDAO()
	followDAO := dao.NewFollowDAO()
	spaceDAO := dao.NewSpaceDAO()
	userManageService := service.NewUserManageService(userDAO, followDAO, spaceDAO)
	userManageController := controller.NewUserManageController(userManageService)
	return userManageController, nil
}

func InitializeCommunityManageController() (*controller.CommunityManageController, error) {
	communityDAO := dao.NewCommunityDAO()
	userDAO := dao.NewUserDAO()
	communityManageService := service.NewCommunityManageService(communityDAO, userDAO)
	communityManageController := controller.NewCommunityManageController(communityManageService)
	return communityManageController, nil
}

func InitializeFileManageController() (*controller.FileManageController, error) {
	spaceDAO := dao.NewSpaceDAO()
	fileManageService := service.NewFileManageService(spaceDAO)
	fileManageController := controller.NewFileManageController(fileManageService)
	return fileManageController, nil
}

func InitializeArticleTypeManageController() (*controller.ArticleTypeManageController, error) {
	articleTypeDAO := dao.NewArticleTypeDAO()
	articleTypeManageService := service.NewArticleTypeManageService(articleTypeDAO)
	articleTypeManageController := controller.NewArticleTypeManageController(articleTypeManageService)
	return articleTypeManageController, nil
}
